/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 
/**
 * 系统动态插件表
 * @export
 * @interface SysPluginCoreReadme
 */
export interface SysPluginCoreReadme {
    /**
     * 雪花Id
     * @type {number}
     * @memberof SysPluginCoreReadme
     */
    id?: number;
    
    /**
     * 插件ID
     * @type {string}
     * @memberof SysPluginCoreReadme
     */
    pluginId: string;
     /**
     * 名称
     * @type {string}
     * @memberof SysPluginCoreReadme
     */
     displayName: string;
      
    /**
     * 备注
     * @type {string}
     * @memberof SysPluginCoreReadme
     */
    content?: string | null;
}
