/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Amount } from './amount';
import { Promotion } from './promotion';
 /**
 * 
 *
 * @export
 * @interface GetRefundDomesticRefundByOutRefundNumberResponse
 */
export interface GetRefundDomesticRefundByOutRefundNumberResponse {

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    message?: string | null;

    /**
     * @type {{ [key: string]: any; }}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    detail?: { [key: string]: any; } | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    refundId?: string | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    outRefundNo?: string | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    transactionId?: string | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    outTradeNo?: string | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    channel?: string | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    userReceivedAccount?: string | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    fundsAccount?: string | null;

    /**
     * @type {string}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    status?: string | null;

    /**
     * @type {Date}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    successTime?: Date | null;

    /**
     * @type {Date}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    createTime?: Date;

    /**
     * @type {Amount}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    amount?: Amount;

    /**
     * @type {Array<Promotion>}
     * @memberof GetRefundDomesticRefundByOutRefundNumberResponse
     */
    promotionDetail?: Array<Promotion> | null;
}
