/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LLMChatHistory } from './llmchat-history';
 /**
 * 聊天摘要历史表
 *
 * @export
 * @interface LLMChatSummaryHistory
 */
export interface LLMChatSummaryHistory {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof LLMChatSummaryHistory
     */
    id?: number;

    /**
     * 用户ID
     *
     * @type {number}
     * @memberof LLMChatSummaryHistory
     */
    userId?: number;

    /**
     * 唯一标识
     *
     * @type {string}
     * @memberof LLMChatSummaryHistory
     */
    uniqueToken?: string | null;

    /**
     * 摘要
     *
     * @type {string}
     * @memberof LLMChatSummaryHistory
     */
    summary?: string | null;

    /**
     * 创建时间
     *
     * @type {number}
     * @memberof LLMChatSummaryHistory
     */
    utcCreateTime?: number;

    /**
     * 聊天历史
     *
     * @type {Array<LLMChatHistory>}
     * @memberof LLMChatSummaryHistory
     */
    histories?: Array<LLMChatHistory> | null;
}
