/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RefundRequestInput
 */
export interface RefundRequestInput {

    /**
     * 商户订单号(原支付交易对应的付款单号)
     *
     * @type {string}
     * @memberof RefundRequestInput
     */
    outTradeNumber?: string | null;

    /**
     * 原订单金额(分)
     *
     * @type {number}
     * @memberof RefundRequestInput
     */
    total?: number;

    /**
     * 退款金额(分)
     *
     * @type {number}
     * @memberof RefundRequestInput
     */
    refund?: number;

    /**
     * 退款原因
     *
     * @type {string}
     * @memberof RefundRequestInput
     */
    reason?: string | null;

    /**
     * 关联的商户订单号
     *
     * @type {string}
     * @memberof RefundRequestInput
     */
    orderId?: string | null;

    /**
     * 关联的商户订单状态(或者为第几次支付，有些订单涉及多次支付，比如先付预付款，后补尾款)
     *
     * @type {string}
     * @memberof RefundRequestInput
     */
    orderStatus?: string | null;

    /**
     * 关联的商户商品编码
     *
     * @type {string}
     * @memberof RefundRequestInput
     */
    merchantGoodsId?: string | null;

    /**
     * 关联的商户商品名称
     *
     * @type {string}
     * @memberof RefundRequestInput
     */
    goodsName?: string | null;

    /**
     * 关联的商户商品单价
     *
     * @type {number}
     * @memberof RefundRequestInput
     */
    unitPrice?: number;

    /**
     * 关联的商户商品退款金额
     *
     * @type {number}
     * @memberof RefundRequestInput
     */
    refundAmount?: number;

    /**
     * 关联的商户商品退货数量
     *
     * @type {number}
     * @memberof RefundRequestInput
     */
    refundQuantity?: number;

    /**
     * 附加数据
     *
     * @type {string}
     * @memberof RefundRequestInput
     */
    attachment?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof RefundRequestInput
     */
    remark?: string | null;
}
