/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CodeGenTypeEnum } from './code-gen-type-enum';
import { YesNoEnum } from './yes-no-enum';
 /**
 * 代码生成模板配置表
 *
 * @export
 * @interface SysCodeGenTemplate
 */
export interface SysCodeGenTemplate {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SysCodeGenTemplate
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SysCodeGenTemplate
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof SysCodeGenTemplate
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SysCodeGenTemplate
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SysCodeGenTemplate
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof SysCodeGenTemplate
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SysCodeGenTemplate
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof SysCodeGenTemplate
     */
    isDelete?: boolean;

    /**
     * 模板文件名
     *
     * @type {string}
     * @memberof SysCodeGenTemplate
     */
    name: string;

    /**
     * @type {CodeGenTypeEnum}
     * @memberof SysCodeGenTemplate
     */
    type?: CodeGenTypeEnum;

    /**
     * @type {YesNoEnum}
     * @memberof SysCodeGenTemplate
     */
    sysFlag?: YesNoEnum;

    /**
     * 是否默认
     *
     * @type {boolean}
     * @memberof SysCodeGenTemplate
     */
    isDefault?: boolean | null;

    /**
     * 输出位置
     *
     * @type {string}
     * @memberof SysCodeGenTemplate
     */
    outputFile: string;

    /**
     * 描述
     *
     * @type {string}
     * @memberof SysCodeGenTemplate
     */
    describe: string;

    /**
     * 排序
     *
     * @type {number}
     * @memberof SysCodeGenTemplate
     */
    orderNo?: number;
}
