/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PlatformTypeEnum } from './platform-type-enum';
 /**
 * 系统三方用户表
 *
 * @export
 * @interface SysOAuthUser
 */
export interface SysOAuthUser {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SysOAuthUser
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SysOAuthUser
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof SysOAuthUser
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SysOAuthUser
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof SysOAuthUser
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof SysOAuthUser
     */
    isDelete?: boolean;

    /**
     * 系统用户Id
     *
     * @type {number}
     * @memberof SysOAuthUser
     */
    userId?: number;

    /**
     * @type {PlatformTypeEnum}
     * @memberof SysOAuthUser
     */
    platformType?: PlatformTypeEnum;

    /**
     * OpenId
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    openId?: string | null;

    /**
     * 会话密钥
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    sessionKey?: string | null;

    /**
     * UnionId
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    unionId?: string | null;

    /**
     * 账号
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    account?: string | null;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    nickName: string;

    /**
     * 头像
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    avatar?: string | null;

    /**
     * 邮箱
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    email?: string | null;

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    mobile?: string | null;

    /**
     * 性别
     *
     * @type {number}
     * @memberof SysOAuthUser
     */
    sex?: number | null;

    /**
     * IP 地址
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    ipAddress?: string | null;

    /**
     * 语言
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    language?: string | null;

    /**
     * 城市
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    city?: string | null;

    /**
     * 省
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    province?: string | null;

    /**
     * 国家
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    country?: string | null;

    /**
     * AccessToken
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    accessToken?: string | null;

    /**
     * RefreshToken
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    refreshToken?: string | null;

    /**
     * 过期时间
     *
     * @type {number}
     * @memberof SysOAuthUser
     */
    expiresIn?: number | null;

    /**
     * 用户授权的作用域，使用逗号分隔
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    scope?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof SysOAuthUser
     */
    remark?: string | null;
}
